"""empty message

Revision ID: 099e45150de0
Revises: f176564255eb
Create Date: 2017-12-27 10:45:35.513266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '099e45150de0'
down_revision = 'f176564255eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    
    op.create_foreign_key(None, 'user', 'access_group', ['group'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    
    # ### end Alembic commands ###
