"""empty message

Revision ID: 182a0e5f4d06
Revises: b2197ecad827
Create Date: 2017-12-20 23:05:16.234685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '182a0e5f4d06'
down_revision = 'b2197ecad827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_log', sa.Column('obs', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_log', 'obs')
    # ### end Alembic commands ###
