"""empty message

Revision ID: 6c6fc11c7494
Revises: 20ecd2181970
Create Date: 2018-01-16 20:16:32.045214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c6fc11c7494'
down_revision = '20ecd2181970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('humiditylog', sa.Column('exported', sa.DateTime(), nullable=True))
    op.add_column('pressurelog', sa.Column('exported', sa.DateTime(), nullable=True))
    op.add_column('templog', sa.Column('exported', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templog', 'exported')
    op.drop_column('pressurelog', 'exported')
    op.drop_column('humiditylog', 'exported')
    # ### end Alembic commands ###
