"""added origin in log table

Revision ID: 989cf6071df0
Revises: 6c6fc11c7494
Create Date: 2018-02-11 15:34:38.729331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '989cf6071df0'
down_revision = '6c6fc11c7494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('origin', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'origin')
    # ### end Alembic commands ###
