"""empty message

Revision ID: b2197ecad827
Revises: 
Create Date: 2017-12-20 22:56:18.940624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2197ecad827'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pressureLog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pressureLog',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('rdate', mysql.DATETIME(), nullable=False),
    sa.Column('sensorLocation', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('value', mysql.FLOAT(), nullable=True),
    sa.Column('sensorType', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('sensor', mysql.VARCHAR(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
