"""empty message

Revision ID: f176564255eb
Revises: 23c2d659bc33
Create Date: 2017-12-27 10:39:36.320702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f176564255eb'
down_revision = '23c2d659bc33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    
    # ### end Alembic commands ###
